#! /bin/bash

present_dir=$(pwd)
echo "Currently in $present_dir"

echo "Deleting previous .vimrc"
rm -rf ~/.vimrc
echo "Making soft link of .vimrc in ~/.vimrc"
ln -s $present_dir/vim/.vimrc ~/.vimrc
echo "Completed creation of .vimrc soft link"
echo "Deleting previous .vim folder"
rm -rf ~/.vim
echo "Creating new .vim and adding custom colorscheme"
mkdir ~/.vim
ln -s $present_dir/vim/colors/ ~/.vim/colors
echo "Cloning and Installing Vundle"
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
echo "Installing plugins"
vim +PluginInstall +qall
nvim +"CocInstall coc-prettier coc-tsserver coc-eslint"
cp ./vim/coc-settings.json ~/.config/nvim/
cp ./vim/init.vim ~/.config/nvim/
