#!/bin/sh

# Start sxhkd for key bindings
# Using bspwm with KDE plasma is causing
# conflicting key bindings, hence redirect errors
# temporarily
# sxhkd

bspc monitor eDP -d I II III IV

bspc config border_width         0
bspc config window_gap           1
bspc config top_padding          70

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Floating windows
bspc rule -a gnome-calculator state=floating follow=on
