#!/bin/sh

bspc monitor eDP -d I II III IV V bg_tasks

bspc config border_width         1
bspc config window_gap           5
bspc config top_padding          65

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Floating windows
bspc rule -a Calculator state=floating follow=on

# Focus follow pointer
bspc config focus_follows_pointer true

# Start sxhkd for key bindings
# Using bspwm with KDE plasma is causing
# conflicting key bindings, hence redirect errors
# temporarily
sxhkd

